package scovmod.model.state.infection;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static scovmod.model.state.infection.InfectionState.*;

public class InfectionTransitions {

	private Map<InfectionState, Set<InfectionState>> permittedTransitions = new HashMap<>();
	
	public InfectionTransitions(){
		permittedTransitions.put(UNDEFINED, setOf(SUSCEPTIBLE));
		permittedTransitions.put(SUSCEPTIBLE, setOf(EXPOSED_YOUNG, EXPOSED_ADULT, EXPOSED_ELDERLY,RECOVERED_YOUNG,RECOVERED_ADULT,RECOVERED_ELDERLY,
				EXPOSED_YOUNG_VARIANT, EXPOSED_ADULT_VARIANT, EXPOSED_ELDERLY_VARIANT,RECOVERED_YOUNG_VARIANT,RECOVERED_ADULT_VARIANT,RECOVERED_ELDERLY_VARIANT));

		permittedTransitions.put(EXPOSED_YOUNG, setOf(RECOVERED_YOUNG,MILD_INFECTIOUS_YOUNG, TRACED_YOUNG));
		permittedTransitions.put(EXPOSED_ADULT, setOf(RECOVERED_ADULT,MILD_INFECTIOUS_ADULT, TRACED_ADULT));
		permittedTransitions.put(EXPOSED_ELDERLY, setOf(RECOVERED_ELDERLY,MILD_INFECTIOUS_ELDERLY, TRACED_ELDERLY));

		permittedTransitions.put(MILD_INFECTIOUS_YOUNG, setOf(RECOVERED_YOUNG,SEVERE_INFECTIOUS_YOUNG,TRACED_YOUNG));
		permittedTransitions.put(MILD_INFECTIOUS_ADULT, setOf(RECOVERED_ADULT,SEVERE_INFECTIOUS_ADULT,TRACED_ADULT));
		permittedTransitions.put(MILD_INFECTIOUS_ELDERLY, setOf(RECOVERED_ELDERLY,SEVERE_INFECTIOUS_ELDERLY,TRACED_ELDERLY));

		permittedTransitions.put(SEVERE_INFECTIOUS_YOUNG, setOf(RECOVERED_YOUNG,HOSPITALISED_YOUNG, DEAD_YOUNG,TRACED_YOUNG));
		permittedTransitions.put(SEVERE_INFECTIOUS_ADULT, setOf(RECOVERED_ADULT,HOSPITALISED_ADULT, DEAD_ADULT,TRACED_ADULT));
		permittedTransitions.put(SEVERE_INFECTIOUS_ELDERLY, setOf(RECOVERED_ELDERLY,HOSPITALISED_ELDERLY,DEAD_ELDERLY,TRACED_ELDERLY));

		permittedTransitions.put(TRACED_YOUNG, setOf(RECOVERED_YOUNG,HOSPITALISED_YOUNG, DEAD_YOUNG));
		permittedTransitions.put(TRACED_ADULT, setOf(RECOVERED_ADULT,HOSPITALISED_ADULT, DEAD_ADULT));
		permittedTransitions.put(TRACED_ELDERLY, setOf(RECOVERED_ELDERLY,HOSPITALISED_ELDERLY,DEAD_ELDERLY));

		permittedTransitions.put(HOSPITALISED_YOUNG, setOf(RECOVERED_YOUNG, DEAD_YOUNG));
		permittedTransitions.put(HOSPITALISED_ADULT, setOf(RECOVERED_ADULT, DEAD_ADULT));
		permittedTransitions.put(HOSPITALISED_ELDERLY, setOf(RECOVERED_ELDERLY, DEAD_ELDERLY));

		permittedTransitions.put(RECOVERED_YOUNG, setOf(SUSCEPTIBLE));
		permittedTransitions.put(RECOVERED_ADULT, setOf(SUSCEPTIBLE));
		permittedTransitions.put(RECOVERED_ELDERLY, setOf(SUSCEPTIBLE));

		permittedTransitions.put(DEAD_YOUNG, setOf());
		permittedTransitions.put(DEAD_ADULT, setOf());
		permittedTransitions.put(DEAD_ELDERLY, setOf());

		//Perimtted transitions for variant states
		permittedTransitions.put(EXPOSED_YOUNG_VARIANT, setOf(RECOVERED_YOUNG_VARIANT,MILD_INFECTIOUS_YOUNG_VARIANT, TRACED_YOUNG_VARIANT));
		permittedTransitions.put(EXPOSED_ADULT_VARIANT, setOf(RECOVERED_ADULT_VARIANT,MILD_INFECTIOUS_ADULT_VARIANT, TRACED_ADULT_VARIANT));
		permittedTransitions.put(EXPOSED_ELDERLY_VARIANT, setOf(RECOVERED_ELDERLY_VARIANT,MILD_INFECTIOUS_ELDERLY_VARIANT, TRACED_ELDERLY_VARIANT));

		permittedTransitions.put(MILD_INFECTIOUS_YOUNG_VARIANT, setOf(RECOVERED_YOUNG_VARIANT,SEVERE_INFECTIOUS_YOUNG_VARIANT,TRACED_YOUNG_VARIANT));
		permittedTransitions.put(MILD_INFECTIOUS_ADULT_VARIANT, setOf(RECOVERED_ADULT_VARIANT,SEVERE_INFECTIOUS_ADULT_VARIANT,TRACED_ADULT_VARIANT));
		permittedTransitions.put(MILD_INFECTIOUS_ELDERLY_VARIANT, setOf(RECOVERED_ELDERLY_VARIANT,SEVERE_INFECTIOUS_ELDERLY_VARIANT,TRACED_ELDERLY_VARIANT));

		permittedTransitions.put(SEVERE_INFECTIOUS_YOUNG_VARIANT, setOf(RECOVERED_YOUNG_VARIANT,HOSPITALISED_YOUNG_VARIANT, DEAD_YOUNG_VARIANT,TRACED_YOUNG_VARIANT));
		permittedTransitions.put(SEVERE_INFECTIOUS_ADULT_VARIANT, setOf(RECOVERED_ADULT_VARIANT,HOSPITALISED_ADULT_VARIANT, DEAD_ADULT_VARIANT,TRACED_ADULT_VARIANT));
		permittedTransitions.put(SEVERE_INFECTIOUS_ELDERLY_VARIANT, setOf(RECOVERED_ELDERLY_VARIANT,HOSPITALISED_ELDERLY_VARIANT,DEAD_ELDERLY_VARIANT,TRACED_ELDERLY_VARIANT));

		permittedTransitions.put(TRACED_YOUNG_VARIANT, setOf(RECOVERED_YOUNG_VARIANT,HOSPITALISED_YOUNG_VARIANT, DEAD_YOUNG_VARIANT));
		permittedTransitions.put(TRACED_ADULT_VARIANT, setOf(RECOVERED_ADULT_VARIANT,HOSPITALISED_ADULT_VARIANT, DEAD_ADULT_VARIANT));
		permittedTransitions.put(TRACED_ELDERLY_VARIANT, setOf(RECOVERED_ELDERLY_VARIANT,HOSPITALISED_ELDERLY_VARIANT,DEAD_ELDERLY_VARIANT));

		permittedTransitions.put(HOSPITALISED_YOUNG_VARIANT, setOf(RECOVERED_YOUNG_VARIANT, DEAD_YOUNG_VARIANT));
		permittedTransitions.put(HOSPITALISED_ADULT_VARIANT, setOf(RECOVERED_ADULT_VARIANT, DEAD_ADULT_VARIANT));
		permittedTransitions.put(HOSPITALISED_ELDERLY_VARIANT, setOf(RECOVERED_ELDERLY_VARIANT, DEAD_ELDERLY_VARIANT));

		permittedTransitions.put(RECOVERED_YOUNG_VARIANT, setOf(SUSCEPTIBLE));
		permittedTransitions.put(RECOVERED_ADULT_VARIANT, setOf(SUSCEPTIBLE));
		permittedTransitions.put(RECOVERED_ELDERLY_VARIANT, setOf(SUSCEPTIBLE));

		permittedTransitions.put(DEAD_YOUNG_VARIANT, setOf());
		permittedTransitions.put(DEAD_ADULT_VARIANT, setOf());
		permittedTransitions.put(DEAD_ELDERLY_VARIANT, setOf());
	}
	
	public boolean permittedTransition(InfectionState from, InfectionState to) {
		return permittedTransitions.get(from).contains(to);
	}
	
	private Set<InfectionState> setOf(InfectionState... states){
		return new HashSet<InfectionState>(Arrays.asList(states));
	}

}
